### ISSUE TITLE
Orcon mechanic ventilation remote not responding

### ISSUE THREAD

**Issue by rregout** [vdbrink/vdbrink.github.io#4]
First of all: great tutorial how to make the Orcon ventilation system smart.

I bought the components from AliExpress and assembled it with your tutorial.

![Orcon_NodeMcU](https://github.com/user-attachments/assets/d8f1565e-7cd5-47cd-ad47-44cc7d3deb57)

I installed ESPHome and added the configuration file on the device.

``` yaml
# Sourcecode by vdbrink.github.io
esphome:
  name: orcon_mcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: <...>
  password: <...>

# Enable logging
logger:

ota:
  - platform: esphome
    password: <...>

# Home Assistant integration
api:

sensor:
  - platform: wifi_signal
    name: "Orcon ESP Signal Strength"
    update_interval: 300s
    
switch:
  - platform: gpio
    pin: D1
    inverted: True
    id: buttonA
  - platform: gpio
    pin: D2
    inverted: True
    id: button1
  - platform: gpio
    pin: D5
    inverted: True
    id: button2
  - platform: gpio
    pin: D6
    inverted: True
    id: button3
  - platform: template
    name: "Mode automatic"
    icon: "mdi:autorenew"
    turn_on_action:
    - switch.turn_on: buttonA
    - delay: 500ms
    - switch.turn_off: buttonA
  - platform: template
    name: "Mode 1"
    icon: "mdi:numeric-1-circle-outline"
    turn_on_action:
    - switch.turn_on: button1
    - delay: 500ms
    - switch.turn_off: button1
  - platform: template
    name: "Mode 2"
    icon: "mdi:numeric-2-circle-outline"
    turn_on_action:
    - switch.turn_on: button2
    - delay: 500ms
    - switch.turn_off: button2
  - platform: template
    name: "Mode 3"
    icon: "mdi:numeric-3-circle-outline"
    turn_on_action:
    - switch.turn_on: button3
    - delay: 500ms
    - switch.turn_off: button3
  ```

The device shows up in Home Assistant:

![HomeAssistant](https://github.com/user-attachments/assets/9d07d8be-cce3-42c9-8a0f-0fa28c8bec9f)

And pressing the buttons are received by the device:

```bash
[07:24:36][D][switch:012]: 'Mode 1' Turning ON.
[07:24:36][D][switch:012]: 'button1' Turning ON.
[07:24:36][D][switch:055]: 'button1': Sending state ON
[07:24:36][D][switch:016]: 'button1' Turning OFF.
[07:24:36][D][switch:055]: 'button1': Sending state OFF
[07:24:39][D][switch:012]: 'Mode 2' Turning ON.
[07:24:39][D][switch:012]: 'button2' Turning ON.
[07:24:39][D][switch:055]: 'button2': Sending state ON
[07:24:39][D][switch:016]: 'button2' Turning OFF.
[07:24:39][D][switch:055]: 'button2': Sending state OFF
[07:24:43][D][switch:012]: 'Mode 3' Turning ON.
[07:24:43][D][switch:012]: 'button3' Turning ON.
[07:24:43][D][switch:055]: 'button3': Sending state ON
[07:24:44][D][switch:016]: 'button3' Turning OFF.
[07:24:44][D][switch:055]: 'button3': Sending state OFF
[07:24:47][D][switch:012]: 'Mode automatic' Turning ON.
[07:24:47][D][switch:012]: 'buttonA' Turning ON.
[07:24:47][D][switch:055]: 'buttonA': Sending state ON
[07:24:47][D][switch:016]: 'buttonA' Turning OFF.
[07:24:47][D][switch:055]: 'buttonA': Sending state OFF
```

The Orcon RF15 remote is paired. But no lights are blinking when pressing the Home Assistant buttons. No effect on the ventilation system.

When I change the ground cable to pin 2, the remote is blinking shortly. But no effect when pressing the Home Assistant buttons.

Any ideas what is wrong in the setup?

**Comment by vdbrink** [comment]
Hi Robert-Jan / @rregout,

Nice to see to create one yourself based on my page!
You're already so close to a working solution!

I know how it feels to have everything connected but it doesn't work, but eventually I got mine working so I hope yours will also work soon. Here are some tips.
It's probably a small thing which is causing the failure so you need to double check (again :) ) all steps.

Can you send a higher resolution photo of the connected adapter? I can't see how this one is connected. It looks from a distance fine but I can't see the wires very clear.

The software defined board type `nodemcuv2` is 100% fine. and the named buttons match the pins.

Some things you can do:
* When you replace the flatcable and plug the original remote to it and press on 1 the ventilation starts working (is the battery on the remote still good enough)? Connect only with the digital circuit is enough, the case is not needed https://vdbrink.github.io/esphome/orcon_images/remote_vs_esp.jpg
* Try a stronger usb power adapter to power the ESP

For the first tests only connect the ground and the pin for mode 1 to D2 and follow the wires matches on the adapter. if this works you can add the other wires also.

Sending the data from the ESP to the flatcable looks fine. So then check step-by-step and connect only one button first:
- check the voltage between d2 and ground when you press the button in HA is 5v for 500ms
- extend the delay time to 1s 
- correct ground pin connected on the board and adapter
- correct D2 on the board and adapter connected
- has the flatcable indeed 8 wires on it
- it the flatcable not upside down (that happened to me because the other side needs to be connected the other way around)
- is the flatcable push far enough in the adapter and remote
- try a new battery in the remote

Good luck!

**Comment by rregout** [comment]
Thanks for al suggestions. I measured the voltage between D2 and the ground and when the button is not pressed it is 3.3v . When the button is pressed it drops to 0.0v and after 500ms back to 3.3v.

Must it be 0.0v and when pressed 5.0v?

**Comment by rregout** [comment]
I figured it out. I reconnected the pins:

Mode 1 on 1
Mode 2 on 2
Mode 3 on 3
Auto on 5
Ground on 7

![IMG_1419](https://github.com/user-attachments/assets/dff0d311-24c5-4d3a-9aef-82dcd01bc6eb)

And it works!

**Comment by vdbrink** [comment]
Great to hear!
Now the fun part begins with the automations.

This also means my documentation is not right? Can you point what is exactly different? https://vdbrink.github.io/esphome/orcon_mechanic_ventilation#connect-the-hardware

This is the original connection table, can you make for me the correct table which works for you then I can add that to the documentation.

| Flat cable +<br>adapter pin | 15RF remote button | Dupont cable color | ESP pin |
|-----------------------------|--------------------|--------------------|---------|
| 1                           | -                  | -                  | -       |
| 2                           | timer*             | -                  | -       |
| 3                           | ground             | purple             | G       |
| 4                           | automatic          | blue               | D1      |
| 5                           | away*              | -                  | -       |
| 6                           | mode 3             | green              | D6      |
| 7                           | mode 2             | yellow             | D5      |
| 8                           | mode 1             | orange             | D2      |

**Comment by rregout** [comment]
I have in some rooms a CO2 sensor (Netatmo). When the CO2 > 1000ppm the Orcon goes to mode 2 and when the CO2 > 2000ppm the Orcon goes to mode 3. When all the rooms < 1000ppm the mode goed to automatic. Works great :)

It seems like the numbering is reversed on my remote (or maybe the adapter) and timer and ground switch places.
The numbering on my remote:

Flat cable +adapter pin | 15RF remote button | Dupont cable color | ESP pin
-- | -- | -- | --
1 | mode 1 | orange | D2
2 | mode 2 | yellow | D5
3 | mode 3 | green | D6
4 | away* | - | -
5 | automatic | blue | D1
6 | timer* | - | -
7 | ground | purple | G
8 | - | - | -
